baseurl: "https://2019.pythonsudeste.org"
title: "Python Sudeste"
canonifyurls: true
theme: "hugo-conference"

GoogleAnalytics: "UA-130207122-1"

params:
  Name: "Python Sudeste 2019"
  Description: "4ª conferência das comunidades Python do Sudeste"
  DatePreConf: "26 de Abril - Tutoriais & Sprints"
  DateConf: "27 e 28 Abril - Palestras"
  #Price: "" # If your event is free, just comment this line
  VenuePreConf: "UCL – Faculdade do Centro Leste"
  VenueConf: "Hotel Senac Ilha do Boi"
  Address: "Hotel Senac Ilha do Boi"
  City:  "Vitória"
  State: "Espírito Santo"
  Images: ["/img/badge.jpg"]
  GoogleMapsKey: "AIzaSyCETwmbTe-1qtV1m8xt_8KR1bcNtKMyeAk"
  Sponsorship: "/PlanoCaptacaoPythonSudeste2019.pdf"
  Call4PapersTutoriais: "https://speakerfight.com/events/python-sudeste-2019-tutoriais/"
  Call4PapersPalestras: "https://speakerfight.com/events/python-sudeste-2019-palestras/"

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - about
    - location
    #- speakers
    #- schedule
    - sponsors
    - partners
    - contact

  # Titles which you can translate to other languages
  Titles:
    about: "Sobre"
    location: "Localização"
    speakers: "Palestrantes"
    schedule: "Agenda"
    sponsors: "Patrocinadores"
    partners: "Parceiros"
    contact: "Contato"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  CallToAction:
    text: "Inscreva-se agora!"
    link: "https://www.eventbrite.com/e/python-sudeste-2019-tickets-55699760483"

  # Fork me on GitHub, if you don't want this, just remove the forkButton property
  # ForkButton:
    # repository: "https://github.com/jweslley/hugo-conference/"

  #About


  # List of Sponsors
  Sponsors:
    - name: "UCL"
      logo: "/img/logo_ucl.png"
      url: "https://www.ucl.br"

  # List of Partners
  Partners:
    - name: "Hotel Ilha do Boi"
      logo: "/img/logohotel.png"
      url: "http://www.hotelilhadoboi.com.br/"

  # The entire schedule
  Schedule:
    - name: "Check-in / Breakfast"
      time: "9h00"

    - name: "Linus Torvalds"
      photo: "/img/speaker.jpg"
      bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
      company: "Linux Foundation"
      link:
        href: "http://twitter.com/linus"
        text: "@linus"
      presentation:
        title: "Digging into a Linux Kernel"
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
        time: "10h00"

    - name: "Bill Gates"
      photo: "/img/speaker.jpg"
      bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
      company: "Microsoft"
      link:
        href: "http://github.com/billy95"
        text: "@billy95"
      presentation:
        title: "Introducing Windows 12"
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
        time: "11h00"

    - name: "Lunch"
      time: "12h00"

    - name: "Chuck Norris"
      photo: "/img/speaker.jpg"
      bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
      company: "Delta Command"
      link:
        href: "http://twitter.com/littlechuck"
        text: "@littlechuck"
      presentation:
        title: "How to kill a elephant with one finger"
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
        time: "13h00"

    - name: "Steve Jobs"
      photo: "/img/speaker.jpg"
      bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
      company: "Apple, Inc."
      link:
        href: "http://github.com/stevie"
        text: "@stevie"
      presentation:
        title: "Presenting iPad"
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
        time: "14h00"

    - name: "Coffee-break"
      time: "15h00"

    - name: "Mark Zuckerberg"
      photo: "/img/speaker.jpg"
      bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
      company: "Facebook"
      link:
        href: "http://twitter.com/zuck"
        text: "@zuck"
      presentation:
        title: "Revealing Facebook Secrets"
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
        time: "16h00"

    - name: "Steve Wozniak"
      photo: "/img/speaker.jpg"
      bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
      company: "Apple, Inc."
      link:
        href: "http://twitter.com/woz"
        text: "@woz"
      presentation:
        title: "Why do I prefer Android over iPhone"
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
        time: "17h00"
